server:
  port: 7020

eureka:
  instance:
    hostname: eureka1
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka1:7020/eureka,http://eureka2:7021/eureka