server:
  port: 7041
spring:
  application:
    name: zuul-gateway

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka1:7020/eureka
    register-with-eureka: false
zuul:
  prefix: /zuul-api
  routes:
    p:
      path: /p/**
      serviceId: provider
  ignored-services: '*'
